# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aws-finetuning-jumpstart-model',
                'doc_host': 'https://AleaxnderYu.github.io',
                'git_url': 'https://github.com/AleaxnderYu/aws-finetuning-jumpstart-model',
                'lib_path': 'aws_finetuning_jumpstart_model'},
  'syms': { 'aws_finetuning_jumpstart_model.core': { 'aws_finetuning_jumpstart_model.core.foo': ( 'core.html#foo',
                                                                                                  'aws_finetuning_jumpstart_model/core.py')}}}
